Repository 0exp/blast_wave, pull requests merged in 2018-08, with the labels that each got.

#1 [middleware] Rack::BlastWave::RequestId middleware
  .rubocop.yml
  .travis.yml
  CHANGELOG.md
  README.md
  bin/console
  blast_wave.gemspec
  lib/blast_wave.rb
  lib/blast_wave/middleware.rb
  lib/blast_wave/request_id.rb
  lib/blast_wave/request_id/extensions/request_interface.rb
  lib/blast_wave/request_id/initializer.rb
  lib/blast_wave/version.rb
  lib/blastwave.rb
  lib/blastwave/version.rb
  spec/features/request_id_spec.rb
  spec/spec_helper.rb
  spec/support/fake_app.rb
  spec/support/request_helpers.rb
Labels: feature

#3 [middlewares] Rack::BlastWave::WhiteList, Rack::BlastWave::BlackList
  CHANGELOG.md
  README.md
  blast_wave.gemspec
  lib/blast_wave.rb
  lib/blast_wave/black_list.rb
  lib/blast_wave/check_list.rb
  lib/blast_wave/check_list/builder.rb
  lib/blast_wave/check_list/checkable.rb
  lib/blast_wave/check_list/checker.rb
  lib/blast_wave/check_list/fail_response.rb
  lib/blast_wave/check_list/filter.rb
  lib/blast_wave/check_list/filter_registry.rb
  lib/blast_wave/request_id.rb
  lib/blast_wave/white_list.rb
  spec/features/black_list_spec.rb
  spec/features/white_list_spec.rb
  spec/support/request_helpers.rb
Labels: feature

#5 [middleware/checklist] Common filters: ip addr list
  lib/blast_wave.rb
  lib/blast_wave/check_list.rb
  lib/blast_wave/check_list/checkable.rb
  lib/blast_wave/check_list/checker.rb
  lib/blast_wave/check_list/common_filters/ip_addrs.rb
  spec/features/black_list_spec.rb
  spec/features/request_id_spec.rb
  spec/features/white_list_spec.rb
Labels: enhancement, feature

#4 Fix 'important' declaration
  README.md
Labels: enhancement

#7 [middleware/checklist] Enhancements and refactorings
  lib/blast_wave/black_list.rb
  lib/blast_wave/black_list/auditor.rb
  lib/blast_wave/black_list/extensions/request_interface.rb
  lib/blast_wave/black_list/initializer.rb
  lib/blast_wave/check_list.rb
  lib/blast_wave/check_list/auditor.rb
  lib/blast_wave/check_list/auditor/result.rb
  lib/blast_wave/check_list/builder.rb
  lib/blast_wave/check_list/checker.rb
  lib/blast_wave/check_list/filter_registry.rb
  lib/blast_wave/request_id.rb
  lib/blast_wave/request_id/extensions/request_interface.rb
  lib/blast_wave/white_list.rb
  lib/blast_wave/white_list/auditor.rb
  lib/blast_wave/white_list/extensions/request_interface.rb
  lib/blast_wave/white_list/initializer.rb
  spec/features/black_list_spec.rb
  spec/features/white_list_spec.rb
  spec/support/request_helpers.rb
Labels: enhancement, refactoring
